## ARREGLOS CON NUMPY

### Declaración de arreglos

In [142]:
import numpy as np
import copy as cp

Definición de arreglos a partir de listas, por ejemplo un de una dimension.

In [93]:
L1=[1,2,3,4,5,6]
print(L1)
print(type(L1))
Arr01=np.array(L1)
print(Arr01)
print(type(Arr01))

[1, 2, 3, 4, 5, 6]
<class 'list'>
[1 2 3 4 5 6]
<class 'numpy.ndarray'>


Para el caso de dos dimensiones se tendria:

In [94]:
Arr02=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(Arr02)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


* Accediendo a los elemetos del arreglo

In [95]:
Arr02[1:2]


array([[4, 5, 6]])

In [96]:
Arr02[1,2]


6

In [97]:
Arr02[1:,1:2]

array([[ 5],
       [ 8],
       [11]])

In [98]:
Arr03=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(Arr03)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


### Tipos de datos 
  
  En los arreglos Python, el tipo de datos es igual para todos los elementos del arreglo.

In [99]:
print(Arr01.dtype)
Arr01=np.array(L1,dtype='float64')
print(Arr01)

int64
[1. 2. 3. 4. 5. 6.]


In [100]:
Arr04=Arr01
Arr04[2]=0
Arr04.astype(bool)

array([ True,  True, False,  True,  True,  True])

otros tipos de datos en http://numpy.org/doc/stable/user/basics.types.html

### Dimensiones

In [101]:
print('Dimension de Arr01: ',Arr01.ndim)
print('Dimension de Arr02: ',Arr02.ndim)
print('Dimension de Arr03: ',Arr03.ndim)

Dimension de Arr01:  1
Dimension de Arr02:  2
Dimension de Arr03:  3


Se puede modificar las dimensiones de un arreglo así:

In [102]:
# MOdificando la dimencion de un arreglo existente axis=0 (filas) axis=1 (columnas)
Arr05=np.expand_dims(Arr04,axis=1)
print(Arr05)
# Al momeno de definir el arreglo
Arr06=np.array(Arr02,ndmin=5)
print(Arr06)

[[1.]
 [2.]
 [0.]
 [4.]
 [5.]
 [6.]]
[[[[[ 1  2  3]
    [ 4  5  6]
    [ 7  8  9]
    [10 11 12]]]]]


Para reducir un arreglo a las dimensiones no vacias estonces:

In [103]:
Arr07=np.squeeze(Arr06)
Arr07.ndim


2

* Creando Arreglos desde Numpy

In [104]:
Arr08=np.arange(2,7)
print(Arr08)
Arr09=np.arange(1,35,7)
print(Arr09)

[2 3 4 5 6]
[ 1  8 15 22 29]


Arreglos especiales 

In [105]:
# Arreglo de ceros
Arr10=np.zeros((5,3))
print('\nCeros Arr10: \n',Arr10)

# Arreglo de unos
Arr11=np.ones((3,8))
print('\nUnos Arr11: \n',Arr11)

# Matriz identica
Arr12=np.eye((4))
print('\nMatriz identica Arr12: \n',Arr12)

# Arreglo equiespaiado
Arr13=np.linspace(0,20,35)
print('\nEquiespaciado Arr13: \n',Arr13)

# Arreglo de aleatorios
Arr14=np.random.rand(2,3)
print('\nAleatorios Arr14: \n',Arr14)

# Arreglo de aleatorios enteros
Arr15=np.random.randint(9,48,25)
print('\nAleatorios enteros Arr15: \n',Arr15)


Ceros Arr10: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Unos Arr11: 
 [[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]

Matriz identica Arr12: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Equiespaciado Arr13: 
 [ 0.          0.58823529  1.17647059  1.76470588  2.35294118  2.94117647
  3.52941176  4.11764706  4.70588235  5.29411765  5.88235294  6.47058824
  7.05882353  7.64705882  8.23529412  8.82352941  9.41176471 10.
 10.58823529 11.17647059 11.76470588 12.35294118 12.94117647 13.52941176
 14.11764706 14.70588235 15.29411765 15.88235294 16.47058824 17.05882353
 17.64705882 18.23529412 18.82352941 19.41176471 20.        ]

Aleatorios Arr14: 
 [[0.74098673 0.60546522 0.60577715]
 [0.80803599 0.36115354 0.06590405]]

Aleatorios enteros Arr15: 
 [43 13 47  9 27 23 38 22 12 11 42 12 18  9 45 32 34 40 35 23 38 34 13 20
 13]


* Forma de un arreglo

Esto nos permite conocer la cantidad de elementos por cada dimension del arreglo

In [106]:
print('\n Tamaño del arreglo Arr12: \n',Arr12.shape)


 Tamaño del arreglo Arr12: 
 (4, 4)


Tambien se puede transformar la estructura de un arreglo:

In [107]:
print('\n Tamaño del arreglo Arr13: \n',Arr13.shape)
Arr16=np.reshape(Arr13,(5,7))
print('\n Tamaño del arreglo Arr16: \n',Arr16.shape)
print(type(Arr16))


 Tamaño del arreglo Arr13: 
 (35,)

 Tamaño del arreglo Arr16: 
 (5, 7)
<class 'numpy.ndarray'>


## FUNCIONES DE NUMPY

In [114]:
# Min, Max, Rango
Arr17=Arr15.reshape(5,5)
print('\n Matriz de enteros aleatorios Arr17 \n',Arr17)
print('\n Elemento minimo del arreglo Arr17: \n',Arr17.min())
print('\n Elemento maximo del arreglo Arr17: \n',Arr17.max())
print('\n Rango del arreglo Arr17: \n',Arr17.ptp())



 Matriz de enteros aleatorios Arr17 
 [[43 13 47  9 27]
 [23 38 22 12 11]
 [42 12 18  9 45]
 [32 34 40 35 23]
 [38 34 13 20 13]]

 Elemento minimo del arreglo Arr17: 
 9

 Elemento maximo del arreglo Arr17: 
 47

 Rango del arreglo Arr17: 
 38


In [109]:

# Min, Max, Rango por cada fila

print('\n Elemento minimo del arreglo por fila Arr17: \n',Arr17.argmin(0))
print('\n Elemento maximo del arreglo por fila Arr17: \n',Arr17.argmax(0))
print('\n Rango del arreglo por fila Arr17: \n',Arr17.ptp(0))

# Min, Max, Rango por cada columna

print('\n Elemento minimo del arreglo por columna Arr17: \n',Arr17.argmin(1))
print('\n Elemento maximo del arreglo por columna Arr17: \n',Arr17.argmax(1))
print('\n Rango del arreglo por columna Arr17: \n',Arr17.ptp(1))


 Elemento minimo del arreglo por fila Arr17: 
 [1 2 4 0 1]

 Elemento maximo del arreglo por fila Arr17: 
 [0 1 0 3 2]

 Rango del arreglo por fila Arr17: 
 [20 26 34 26 34]

 Elemento minimo del arreglo por columna Arr17: 
 [3 4 3 4 2]

 Elemento maximo del arreglo por columna Arr17: 
 [2 1 4 2 0]

 Rango del arreglo por columna Arr17: 
 [38 27 36 17 25]


## Estadisticas básicas

In [110]:
# Percentile, mediana, media, desviacion estándar, varianza
print('\n Percentil 35 del arreglo Arr17: \n',np.percentile(Arr17,35))
print('\n Mediana del arreglo Arr17: \n',np.median(Arr17))
print('\n Varianza del arreglo Arr17: \n',np.var(Arr17))
print('\n Desv. estándar del arreglo Arr17: \n',np.std(Arr17))
print('\n Media del arreglo Arr17: \n',np.mean(Arr17))


 Percentil 35 del arreglo Arr17: 
 18.799999999999997

 Mediana del arreglo Arr17: 
 23.0

 Varianza del arreglo Arr17: 
 156.5056

 Desv. estándar del arreglo Arr17: 
 12.51021982220936

 Media del arreglo Arr17: 
 26.12


### Ordenamiento

In [112]:
print('\n Ordenando el arreglo Arr15: \n',np.sort(Arr15))



 Ordenando el arreglo Arr15: 
 [ 9  9 11 12 12 13 13 13 18 20 22 23 23 27 32 34 34 35 38 38 40 42 43 45
 47]


### Concatenacion

In [144]:
#print('\n \n',Arr)
print('\n Tamaño del arreglo Arr10:',Arr10.shape)
print(' Tamaño del arreglo Arr17:',Arr17.shape)
Arr18=np.concatenate((Arr17,Arr10),axis=1)
print('\n Concatenación del arreglo Arr17 y Arr10 por columnas: \n',Arr18)

print('\n\n Tamaño del arreglo Arr07:',Arr07.shape)
Arr19=np.concatenate((Arr07,Arr10),axis=0)
print('\n Concatenación del arreglo Arr07 y Arr10 por filas: \n',Arr19)



 Tamaño del arreglo Arr10: (5, 3)
 Tamaño del arreglo Arr17: (5, 5)

 Concatenación del arreglo Arr17 y Arr10 por columnas: 
 [[43. 13. 47.  9. 27.  0.  0.  0.]
 [23. 38. 22. 12. 11.  0.  0.  0.]
 [42. 12. 18.  9. 45.  0.  0.  0.]
 [32. 34. 40. 35. 23.  0.  0.  0.]
 [38. 34. 13. 20. 13.  0.  0.  0.]]


 Tamaño del arreglo Arr07: (4, 3)

 Concatenación del arreglo Arr07 y Arr10 por filas: 
 [[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


### Transpuesta de un arreglo

In [145]:
Arr20=cp.copy(Arr19.T)
print(Arr20)

[[ 1.  4.  7. 10.  0.  0.  0.  0.  0.]
 [ 2.  5.  8. 11.  0.  0.  0.  0.  0.]
 [ 3.  6.  9. 12.  0.  0.  0.  0.  0.]]


### Copy

La modificación de objetos tras la reasignacion puede cambiar el arreglo original, lo cua se ilustra a continuación:

In [146]:
Arr21=Arr20[:,2:6]
print('\nArreglo 21 inicial \n',Arr21)
Arr21[:,1]=100*Arr21[:,1]
print('\nArreglo 21 modificado \n',Arr21)
print('\nArreglo 20 \n',Arr20)


Arreglo 21 inicial 
 [[ 7. 10.  0.  0.]
 [ 8. 11.  0.  0.]
 [ 9. 12.  0.  0.]]

Arreglo 21 modificado 
 [[   7. 1000.    0.    0.]
 [   8. 1100.    0.    0.]
 [   9. 1200.    0.    0.]]

Arreglo 20 
 [[1.0e+00 4.0e+00 7.0e+00 1.0e+03 0.0e+00 0.0e+00 0.0e+00 0.0e+00 0.0e+00]
 [2.0e+00 5.0e+00 8.0e+00 1.1e+03 0.0e+00 0.0e+00 0.0e+00 0.0e+00 0.0e+00]
 [3.0e+00 6.0e+00 9.0e+00 1.2e+03 0.0e+00 0.0e+00 0.0e+00 0.0e+00 0.0e+00]]


lo correcto sería generar primero una copia del arreglo para lo cual hay varias opciones, una de ellas usando el comando copy de la libreria copy.

In [149]:
Arr20=cp.copy(Arr19.T)
print(Arr19.astype('int32'))
Arr22=Arr20[:,2:6]*1
print('\nArreglo 22 inicial \n',Arr22)
Arr22[:,1]=100*Arr22[:,1]
print('\nArreglo 22 modificado \n',Arr22)
print('\nArreglo 20 \n',Arr20)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [ 0  0  0]
 [ 0  0  0]
 [ 0  0  0]
 [ 0  0  0]
 [ 0  0  0]]

Arreglo 22 inicial 
 [[ 7. 10.  0.  0.]
 [ 8. 11.  0.  0.]
 [ 9. 12.  0.  0.]]

Arreglo 22 modificado 
 [[   7. 1000.    0.    0.]
 [   8. 1100.    0.    0.]
 [   9. 1200.    0.    0.]]

Arreglo 20 
 [[ 1.  4.  7. 10.  0.  0.  0.  0.  0.]
 [ 2.  5.  8. 11.  0.  0.  0.  0.  0.]
 [ 3.  6.  9. 12.  0.  0.  0.  0.  0.]]


### Condiciones sobre arreglos
  
  Esto es una forma de filtros sobre arreglos

In [154]:
#print('\n \n',Arr)
Arr23=Arr13<10
print('\n Lista Booleana bajo la condicion\n',Arr23)
ind_Arr23=Arr13<10
Arr24=Arr13[ind_Arr23]
print('\n Arreglo filtrado bajo la condicion\n',Arr24)


 Lista Booleana bajo la condicion
 [ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True False False False False False False False
 False False False False False False False False False False False]

 Areglo filtrado bajo la condicion
 [0.         0.58823529 1.17647059 1.76470588 2.35294118 2.94117647
 3.52941176 4.11764706 4.70588235 5.29411765 5.88235294 6.47058824
 7.05882353 7.64705882 8.23529412 8.82352941 9.41176471]


haciendolo directamente se tendria:

In [155]:
Arr25=Arr13[Arr13<10]
print('\n Arreglo filtrado directamente bajo la condicion\n',Arr25)


 Arreglo filtrado directamente bajo la condicion
 [0.         0.58823529 1.17647059 1.76470588 2.35294118 2.94117647
 3.52941176 4.11764706 4.70588235 5.29411765 5.88235294 6.47058824
 7.05882353 7.64705882 8.23529412 8.82352941 9.41176471]


## Operaciones con arreglos y escalares

In [160]:
print('\nArreglo 8 \n',Arr08)
Arr26=Arr08*2
print('\nMultiplicacion por un escalar  \n',Arr26)
Arr27=Arr08+2
print('\nSuma de un escalar  \n',Arr27)


Arreglo 8 
 [2 3 4 5 6]

Multiplicacion por un escalar  
 [ 4  6  8 10 12]

Suma de un escalar  
 [4 5 6 7 8]


### Operaciones entre arreglos

In [177]:
Arr28=cp.copy(Arr09.reshape((1,5)))
print('\n Tamaño del arreglo Arr28: ',Arr28.shape)
print('\n Tamaño del arreglo Arr17: ',Arr17.shape)

Arr29=np.matmul(Arr28,Arr17)
Arr30=Arr28@Arr17
print('\n Arreglo resultante de la multiplicacion:\n ',Arr29,'\n', Arr30)

Arr31=np.matmul(Arr17,Arr28.T)
Arr32=Arr17@Arr28.T
print('\n Arreglo resultante de la multiplicacion: \n',Arr31,'\n\n', Arr32)



 Tamaño del arreglo Arr28:  (1, 5)

 Tamaño del arreglo Arr17:  (5, 5)

 Arreglo resultante de la multiplicacion:
  [[2663 2231 1750 1590 1673]] 
 [[2663 2231 1750 1590 1673]]

 Arreglo resultante de la multiplicacion: 
 [[1833]
 [1240]
 [1911]
 [2341]
 [1322]] 

 [[1833]
 [1240]
 [1911]
 [2341]
 [1322]]

Valores aleatorios 
 [[9]
 [1]
 [5]
 [4]
 [6]]


In [179]:

Arr33=np.random.randint(0,10,5).reshape((5,1))
print('\nValores aleatorios \n',Arr33)
Arr34=Arr32+Arr33
print('Arreglo suma \n',Arr34)


Valores aleatorios 
 [[3]
 [8]
 [0]
 [5]
 [6]]
Arreglo suma 
 [[1836]
 [1248]
 [1911]
 [2346]
 [1328]]
